### ISSUE TITLE
Circuit

### ISSUE THREAD

**Issue by philspitlerSF** [hamsafar/POV#1]
I would love to see you you have wired the circuit and positioned the hall sensor etc.

Looks like a great project, thanks for sharing.

**Comment by AlirezaAbdiyan** [comment]
For transmit electrical I used car generator collector:
[https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1hFzOi26pRN8HJvZpye_M6zapPL-WdzIn2V7uTxjS9C74iBW7](url)

[https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCwvs-cBSmy5ja7feiEZnvOAb49Z88UENwQfPnYlTdj7GDxrMF](url)

And for check position I used UGN3144.
